### ISSUE TITLE
Identify potential nodes of concern 

### ISSUE THREAD

**Issue by cyberorg** [ketan/paragliding-meshmap#63]
Any active non-static node stationary for over 30 min outside 1KM of LZ could be marked in orange.

Not sure if there is a way to get AGL, it could be used to detect someone is in air, check AGL outside the LZ radius, compare change in AGL, if AGL is > 200M the device is in air, if it stays below 50M for half an hour after being seen > 200M then the glider could be in trouble. On map it would be easy to see if they landed in a clear area.

This might help: 
https://chatgpt.com/share/5ee30271-d04a-4995-ac39-8122a7e97b8c

**Comment by stefwalter** [comment]
After chatting with @ketan ... idea is to use the SRTM [Shuttle Radar Topography Mission](https://www.usgs.gov/centers/eros/science/usgs-eros-archive-digital-elevation-shuttle-radar-topography-mission-srtm?qt-science_center_objects=0#qt-science_center_objects)

We can use this NPM package: 

https://www.npmjs.com/package/srtm-elevation

Current thinking is to get the dataset locally for the server to query, rather than using an API to a third party service.

Fetching URLs like this (per lat, long pair) seems to work (this is for N57, E011):

https://srtm.fasma.org/N57E011.SRTMGL3S.hgt.zip

**Comment by cyberorg** [comment]
New idea we discussed is to detect flying nodes and mark them in Blue, the ones on the ground green and those offline marked same as now.

**Comment by ketan** [comment]
Closed via #110
